# Generated by Django 4.1.1 on 2023-01-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='file_upload',
            fields=[
                ('ids', models.AutoField(primary_key=True, serialize=False)),
                ('myfile', models.FileField(upload_to='')),
            ],
        ),
    ]
